index_name = "estasklog"
task_actions = "*search,*scroll"
monitor_envs = ["prod"]
write_data_es = ["http://192.168.32.14:9200", "http://192.168.32.15:9200", "http://192.168.32.16:9200"]
write_data_es_user = "elastic"
write_data_es_password = "123456"